services:
  backend:
    build:
      context: ./backend
    container_name: workshops-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/db.sqlite3:/backend/db.sqlite3
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    container_name: workshops-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    restart: unless-stopped
